name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest,windows-latest]
        go-version: [ '1.17', '1.18', '1.19' ]
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GOPRIVATE: github.com/vfdcloud/*
    steps:
      - uses: actions/checkout@v3
      - name: set up git
        run:  git config --global url."https://$GH_ACCESS_TOKEN:@github.com/".insteadOf "https://github.com"
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .